name: weather_app
description: Weather app project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  weather_icons: ^3.0.0
  flutter_riverpod: ^2.3.5
  dio: ^5.0.1
  shared_preferences: ^2.0.13
  carousel_slider: ^4.2.1
  either_dart: ^0.3.0
  go_router: ^6.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true